In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
df.shape

(10000, 11)

In [6]:
df['fuel_type'].nunique()

3

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
print(df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max())

41.2

In [9]:
#median of the horsepower column
print(df['horsepower'].median())

254.0

In [10]:
# most frequent value in the horse power column
most_freq_val = df['horsepower'].mode()[0]
print(most_freq_val)

252.0

In [11]:
# fill the horse power column with the most frequent value in the column
df['horsepower'] = df['horsepower'].fillna(most_freq_val)

In [12]:
# check the column again
df['horsepower'].isnull().sum()

np.int64(0)

In [13]:
# calculate the median value of horsepower again

print(df['horsepower'].median())

252.0

In [14]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [15]:
# select all cars from Asia
asia_cars = df.loc[df['origin'] == 'Asia', ['vehicle_weight', 'model_year']].head(7)

In [16]:
asia_cars

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [17]:
X = asia_cars.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [18]:
X.shape

(7, 2)

In [19]:
XTX = X.T @ X

In [20]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [21]:
XTX.shape

(2, 2)

In [22]:
XTX_inv = np.linalg.inv(XTX)

In [23]:
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [24]:
[1100, 1300, 800, 900, 1000, 1100, 1200]

[1100, 1300, 800, 900, 1000, 1100, 1200]

In [25]:
# create an array y

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [26]:
w = XTX_inv.dot(X.T.dot(y))

In [27]:
w

array([0.13644777, 0.2327492 ])

In [30]:
print(w.sum())

0.3691969690492593