In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.6'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [4]:
df.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

In [5]:
import numpy as np

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1, 2, 3, 5, 7, 12])

In [10]:
a

array([ 1,  2,  3,  5,  7, 12])

In [11]:
a[2]

np.int64(3)

In [12]:
a[2] = 10

In [13]:
a

array([ 1,  2, 10,  5,  7, 12])

In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [16]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### Multi-dimensional Arrays

In [17]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [19]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
n[1, :]

array([4, 5, 6])

In [21]:
n[:, 2]

array([3, 6, 9])

In [22]:
n[1, 1:]

array([5, 6])

### Randomly Generated Arrays

In [23]:
np.random.seed(2) # to avoid reproducibilty
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [24]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [25]:
np.random.seed(2)
np.random.randint(low = 0, high = 100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise Operations

In [26]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [27]:
a + 1

array([1, 2, 3, 4, 5])

In [28]:
a * 2

array([0, 2, 4, 6, 8])

In [29]:
a/ 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [30]:
b = (10 + (a * 2)) ** 2 / 100

In [31]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [32]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

### Comparison Operations

In [33]:
a

array([0, 1, 2, 3, 4])

In [34]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [35]:
a >= 2

array([False, False,  True,  True,  True])

In [36]:
a > b

array([False, False,  True,  True,  True])

In [37]:
a[a > b]

array([2, 3, 4])

### Summarizing Operations

In [38]:
a.min()

np.int64(0)

In [39]:
a.max()

np.int64(4)

In [40]:
a.sum()

np.int64(10)

In [41]:
a.mean()

np.float64(2.0)

In [42]:
a.std()

np.float64(1.4142135623730951)

### Vector Operations

In [43]:
a = np.array([2, 4, 5, 6])
a

array([2, 4, 5, 6])

In [44]:
a * 2

array([ 4,  8, 10, 12])

In [45]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [46]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [47]:
a

array([2, 4, 5, 6])

In [48]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [49]:
a + v

array([3, 4, 5, 8])

### Multiplication

In [50]:
a.shape[0]

4

In [51]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [52]:
vector_vector_multiplication(a, v)

np.float64(14.0)

In [53]:
a.dot(v)

np.int64(14)

In [54]:
# Matrix-vector multiplication
v

array([1, 0, 0, 2])

In [55]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [56]:
v = np.array([1, 0.5, 2, 1])
v

array([1. , 0.5, 2. , 1. ])

In [57]:
U.shape[1]

4

In [58]:
v.shape[0]

4

In [59]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [60]:
matrix_vector_multiplication(U,v)

array([20. ,  6. ,  8.5])

In [61]:
U.dot(v)

array([20. ,  6. ,  8.5])

In [62]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]])

V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [65]:
U.shape[1]

4

In [66]:
V.shape[0]

4

In [75]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [76]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [77]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity Matrix

In [78]:
I = np.eye(3)

In [79]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Matrix Inverse

In [81]:
Vs = V[[0, 1, 2]]

In [82]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [84]:
Vs_inv = np.linalg.inv(Vs)

Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [86]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])